TZN-250 Update documentation format
NexPlayer/TizenWebOS pull request #3
Opened 2022-04-07 12:48 UTC by yasinex

2022-04-07 13:33 UTC, Kuzy15 approved these changes

2022-05-12 08:36 UTC, AndyLuiNexplayer requested changes
I found just that typo error, I checked and updated more typo errors but that one I just found it. If you can change it and solve the merge conflicts.

2022-05-12 08:36 UTC, AndyLuiNexplayer commented on ps5/api.md
> +?> Please note that the default value of the <b>autoplay</b> parameter is true, so the player will star without any user action.
typo error: the player will **START** without any

2022-05-12 15:38 UTC, AndyLuiNexplayer approved these changes

2022-05-13 07:42 UTC, merged